In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(r"C:\Users\Mr\OneDrive\Documents\Rekha DA\Projects for resume\Global Sales\Global.superstore.csv")

In [6]:
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

In [7]:
df.shape

(51290, 27)

In [8]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', '记录数', 'Order.Date', 'Order.ID', 'Order.Priority',
       'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID',
       'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   记录数             51290 non-null  int64
 8   Order.Date      51290 non-null  object
 9   Order.ID        51290 non-null  object
 10  Order.Priority  51290 non-null  object
 11  Product.ID      51290 non-null  object
 12  Product.Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row.ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship.Date       51290 non-null  object
 20  Ship.Mode       51290 non-null  object
 21  Shipping.Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub.Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

In [10]:
df.describe()

,Discount,记录数,Profit,Quantity,Row.ID,Sales,Shipping.Cost,Year,weeknum
count,51290.000000,51290.0,51290.000000,51290.000000,51290.00000,51290.000000,51290.000000,51290.000000,51290.000000
mean,0.142908,1.0,28.610982,3.476545,25645.50000,246.498440,26.375818,2012.777208,31.287112
std,0.212280,0.0,174.340972,2.278766,14806.29199,487.567175,57.296810,1.098931,14.429795
min,0.000000,1.0,-6599.978000,1.000000,1.00000,0.000000,0.002000,2011.000000,1.000000
25%,0.000000,1.0,0.000000,2.000000,12823.25000,31.000000,2.610000,2012.000000,20.000000
50%,0.000000,1.0,9.240000,3.000000,25645.50000,85.000000,7.790000,2013.000000,33.000000
75%,0.200000,1.0,36.810000,5.000000,38467.75000,251.000000,24.450000,2014.000000,44.000000
max,0.850000,1.0,8399.976000,14.000000,51290.00000,22638.000000,933.570000,2014.000000,53.000000

In [11]:
df.isnull().sum()

Category          0
City              0
Country           0
Customer.ID       0
Customer.Name     0
Discount          0
Market            0
记录数               0
Order.Date        0
Order.ID          0
Order.Priority    0
Product.ID        0
Product.Name      0
Profit            0
Quantity          0
Region            0
Row.ID            0
Sales             0
Segment           0
Ship.Date         0
Ship.Mode         0
Shipping.Cost     0
State             0
Sub.Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   记录数             51290 non-null  int64
 8   Order.Date      51290 non-null  object
 9   Order.ID        51290 non-null  object
 10  Order.Priority  51290 non-null  object
 11  Product.ID      51290 non-null  object
 12  Product.Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row.ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship.Date       51290 non-null  object
 20  Ship.Mode       51290 non-null  object
 21  Shipping.Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub.Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

In [14]:
df.columns=df.columns.str.replace('.','_',regex=False)

In [15]:
df.columns

Index(['Category', 'City', 'Country', 'Customer_ID', 'Customer_Name',
       'Discount', 'Market', '记录数', 'Order_Date', 'Order_ID', 'Order_Priority',
       'Product_ID', 'Product_Name', 'Profit', 'Quantity', 'Region', 'Row_ID',
       'Sales', 'Segment', 'Ship_Date', 'Ship_Mode', 'Shipping_Cost', 'State',
       'Sub_Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [16]:
df["Order_Date"]=pd.to_datetime(df["Order_Date"])
df["Ship_Date"]=pd.to_datetime(df["Ship_Date"])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer_ID     51290 non-null  object
 4   Customer_Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   记录数             51290 non-null  int64
 8   Order_Date      51290 non-null  datetime64[ns]
 9   Order_ID        51290 non-null  object
 10  Order_Priority  51290 non-null  object
 11  Product_ID      51290 non-null  object
 12  Product_Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row_ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship_Date       51290 non-null  datetime64[ns]
 20  Ship_Mode       51290 non-null  object
 21  Shipping_Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub_Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(6), object(16)
memory usage: 10.6+ MB

In [18]:
df["Shipping_Days"] = (df["Ship_Date"] - df["Order_Date"]).dt.days

In [19]:
df[["Order_Date","Ship_Date","Shipping_Days"]].head()

  Order_Date  Ship_Date  Shipping_Days
0 2011-01-07 2011-01-09              2
1 2011-01-21 2011-01-26              5
2 2011-08-05 2011-08-09              4
3 2011-08-05 2011-08-09              4
4 2011-09-29 2011-10-03              4

In [20]:
df["Order_Year"] = df["Order_Date"].dt.year

In [21]:
df["Order_Month"]=df["Order_Date"].dt.month_name()

In [22]:
df["Quarter"]=df["Order_Date"].dt.quarter

In [23]:
df["Profit_Margin"] = (df["Profit"] / df["Sales"]) * 100

In [24]:
df["Product_Short_Name"] = df["Product_Name"].apply(
    lambda x: x[:35] + "..." if len(x) > 35 else x
)

In [25]:
df["记录数"].value_counts()

记录数
1    51290
Name: count, dtype: int64

In [26]:
df.iloc[:, 7].value_counts()

记录数
1    51290
Name: count, dtype: int64

In [27]:
df.drop(df.columns[7], axis=1, inplace=True)

In [28]:
for col in df.columns:
    print(col)

Category
City
Country
Customer_ID
Customer_Name
Discount
Market
Order_Date
Order_ID
Order_Priority
Product_ID
Product_Name
Profit
Quantity
Region
Row_ID
Sales
Segment
Ship_Date
Ship_Mode
Shipping_Cost
State
Sub_Category
Year
Market2
weeknum
Shipping_Days
Order_Year
Order_Month
Quarter
Profit_Margin
Product_Short_Name

In [29]:
df.columns = df.columns.str.strip()
print(df.columns.tolist())

['Category', 'City', 'Country', 'Customer_ID', 'Customer_Name', 'Discount', 'Market', 'Order_Date', 'Order_ID', 'Order_Priority', 'Product_ID', 'Product_Name', 'Profit', 'Quantity', 'Region', 'Row_ID', 'Sales', 'Segment', 'Ship_Date', 'Ship_Mode', 'Shipping_Cost', 'State', 'Sub_Category', 'Year', 'Market2', 'weeknum', 'Shipping_Days', 'Order_Year', 'Order_Month', 'Quarter', 'Profit_Margin', 'Product_Short_Name']

In [30]:
df.to_csv("Global_Superstore_Cleaned.csv", index=False)

In [31]:
df.columns

Index(['Category', 'City', 'Country', 'Customer_ID', 'Customer_Name',
       'Discount', 'Market', 'Order_Date', 'Order_ID', 'Order_Priority',
       'Product_ID', 'Product_Name', 'Profit', 'Quantity', 'Region', 'Row_ID',
       'Sales', 'Segment', 'Ship_Date', 'Ship_Mode', 'Shipping_Cost', 'State',
       'Sub_Category', 'Year', 'Market2', 'weeknum', 'Shipping_Days',
       'Order_Year', 'Order_Month', 'Quarter', 'Profit_Margin',
       'Product_Short_Name'],
      dtype='object')

In [33]:
df.shape

(51290, 32)

In [34]:
# KPI 1 
# Calculate the total sales of the company
Total_Sales=df["Sales"].sum()
# Convert to millions
Total_Sales_M=Total_Sales/1_000_000
# Display the result
print(f"Total Sales: {Total_Sales_M:.2f}M")

Total Sales: 12.64M

In [35]:
# Calculate the Total Profit
Total_Profit=df["Profit"].sum()
# Dispaly the result
Total_Profit

np.float64(1467457.2912800002)

In [36]:
#KPI2 
# Calculate the Total Profit
total_profit=df["Profit"].sum()/1_000_000
# Dispaly the result# display in Millions
print(f"Total Profit: {total_profit:,.2f}M")

Total Profit: 1.47M

In [37]:
#KPI 3 
# Calculate the totak orders of unique orders
total_orders=df["Order_ID"].nunique()
# Display the result 
print(f"Total Orders: {total_orders:,}")

Total Orders: 25,035

In [38]:
# KPI 4 Customers
# calculate the total customers
total_customers=df["Customer_ID"].nunique()
print(f"Total Customers:{total_customers:,}")

Total Customers:4,873

In [39]:
# AVG sales per order
average_sales=df["Sales"].mean()
print(f"Avg Sales:{average_sales:,.2f}")

Avg Sales:246.50

In [40]:
# AVG sales per order
average_profit=df["Profit"].mean()
print(f"Avg Profit:{average_profit:,.2f}")

Avg Profit:28.61

In [41]:
#BUSINESS ANALYSIS (EDA)
# Which Category Generates the Highest Sales?
# Categorywise sales analysis
category_sales = df.groupby("Category")["Sales"].sum().sort_values(ascending=False)
(category_sales)

Category
Technology         4744691
Furniture          4110884
Office Supplies    3787330
Name: Sales, dtype: int64

In [42]:
# category wise profit
#Which Category Generates the Highest Profit?
category_profit=df.groupby("Category")["Profit"].sum().sort_values(ascending=False)
category_profit

Category
Technology         663778.73318
Office Supplies    518473.83430
Furniture          285204.72380
Name: Profit, dtype: float64

In [43]:
# Region-wise Sales Analysis
#Which Region Has the Highest Sales
Region_sales=df.groupby("Region")["Sales"].sum().sort_values(ascending = False)
print(Region_sales)

Region
Central           2822399
South             1600960
North             1248192
Oceania           1100207
Southeast Asia     884438
North Asia         848349
EMEA               806184
Africa             783776
Central Asia       752839
West               725514
East               678834
Caribbean          324281
Canada              66932
Name: Sales, dtype: int64

In [44]:
# Top 10 Cutomer by sales
top_customers_sales=(df.groupby("Customer_Name")["Sales"].sum().sort_values(ascending=False).head(10))

print(top_customers_sales.round(2))

Customer_Name
Tom Ashbrook          40489
Tamara Chand          37453
Greg Tran             35552
Christopher Conant    35187
Sean Miller           35170
Bart Watters          32315
Natalie Fritzler      31778
Fred Hopkins          30404
Jane Waco             30288
Hunter Lopez          30246
Name: Sales, dtype: int64

In [45]:
# Top 10 customers by profit
top_customers_profit=(df.groupby("Customer_Name")["Profit"].sum().sort_values(ascending = False).head(10))
print(top_customers_profit.round(2))

Customer_Name
Tamara Chand       8672.90
Raymond Buch       8453.05
Sanjit Chand       8205.38
Hunter Lopez       7816.57
Bill Eplett        7410.01
Harry Marie        6958.29
Susan Pistek       6484.41
Mike Gockenbach    6458.68
Adrian Barton      6417.28
Tom Ashbrook       6311.98
Name: Profit, dtype: float64

In [46]:
# Top 10 Products by Sales
top_product_sale=(df.groupby("Product_Name")["Sales"].sum().sort_values(ascending =False).head(10))
print(top_product_sale.round(2))

Product_Name
Apple Smart Phone, Full Size                                86936
Cisco Smart Phone, Full Size                                76441
Motorola Smart Phone, Full Size                             73159
Nokia Smart Phone, Full Size                                71904
Canon imageCLASS 2200 Advanced Copier                       61600
Hon Executive Leather Armchair, Adjustable                  58200
Office Star Executive Leather Armchair, Adjustable          50667
Harbour Creations Executive Leather Armchair, Adjustable    50120
Samsung Smart Phone, Cordless                               48654
Nokia Smart Phone, with Caller ID                           47880
Name: Sales, dtype: int64

In [47]:
#Top 10 Products by Profit
top_product_profit=(df.groupby("Product_Name")["Profit"].sum().sort_values(ascending = False).head(10))
print(top_product_profit.round(2))

Product_Name
Canon imageCLASS 2200 Advanced Copier                       25199.93
Cisco Smart Phone, Full Size                                17238.52
Motorola Smart Phone, Full Size                             17027.11
Hoover Stove, Red                                           11807.97
Sauder Classic Bookcase, Traditional                        10672.07
Harbour Creations Executive Leather Armchair, Adjustable    10427.33
Nokia Smart Phone, Full Size                                 9938.20
Cisco Smart Phone, with Caller ID                            9786.64
Nokia Smart Phone, with Caller ID                            9465.33
Belkin Router, USB                                           8955.02
Name: Profit, dtype: float64

In [48]:
df["Order_Month"].unique()

array(['January', 'August', 'September', 'October', 'November',
       'December', 'February', 'March', 'April', 'June', 'May', 'July'],
      dtype=object)

In [49]:
df["Order_Month"] = df["Order_Date"].dt.month_name()

In [50]:
df["Order_Month"].value_counts()

Order_Month
November     6342
December     6302
September    5975
June         5331
August       5078
October      4490
May          3747
July         3166
April        3057
March        3035
January      2599
February     2168
Name: count, dtype: int64

In [51]:
# Monthly Sales Trend
df["Order_Month"] = df["Order_Date"].dt.month_name()

In [52]:
df["Order_Month"].value_counts().sort_index()

Order_Month
April        3057
August       5078
December     6302
February     2168
January      2599
July         3166
June         5331
March        3035
May          3747
November     6342
October      4490
September    5975
Name: count, dtype: int64

In [53]:
df["Order_Date"].head(10)

0   2011-01-07
1   2011-01-21
2   2011-08-05
3   2011-08-05
4   2011-09-29
5   2011-10-19
6   2011-11-04
7   2011-11-12
8   2011-11-22
9   2011-12-05
Name: Order_Date, dtype: datetime64[ns]

In [54]:
# Create Order Month from Order Date
df["Order_Month"] = df["Order_Date"].dt.month_name()

# Verify the result
df["Order_Month"].value_counts().sort_index()

Order_Month
April        3057
August       5078
December     6302
February     2168
January      2599
July         3166
June         5331
March        3035
May          3747
November     6342
October      4490
September    5975
Name: count, dtype: int64

In [55]:
month_order = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
]

monthly_sales = (
    df.groupby("Order_Month")["Sales"]
      .sum()
      .reindex(month_order)
)

# Convert to Millions
monthly_sales = monthly_sales / 1_000_000

print(monthly_sales.round(2))

Order_Month
January      0.68
February     0.54
March        0.77
April        0.70
May          0.90
June         1.27
July         0.75
August       1.29
September    1.44
October      1.17
November     1.55
December     1.58
Name: Sales, dtype: float64

In [56]:
#Yearly Sales Trend
yearly_sales = df.groupby("Year")["Sales"].sum()

print(yearly_sales.round(2))

Year
2011    2259511
2012    2677493
2013    3405860
2014    4300041
Name: Sales, dtype: int64

In [57]:
# Rename columns
df.columns = df.columns.str.replace('.', '_', regex=False)

# Convert date columns
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Ship_Date"] = pd.to_datetime(df["Ship_Date"])

In [58]:
df["Order_Date"].head()

0   2011-01-07
1   2011-01-21
2   2011-08-05
3   2011-08-05
4   2011-09-29
Name: Order_Date, dtype: datetime64[ns]

In [59]:
df[["Order_Date", "Ship_Date"]].head(10)

  Order_Date  Ship_Date
0 2011-01-07 2011-01-09
1 2011-01-21 2011-01-26
2 2011-08-05 2011-08-09
3 2011-08-05 2011-08-09
4 2011-09-29 2011-10-03
5 2011-10-19 2011-10-19
6 2011-11-04 2011-11-11
7 2011-11-12 2011-11-16
8 2011-11-22 2011-11-26
9 2011-12-05 2011-12-10

In [60]:
df["Year"].value_counts().sort_index()

Year
2011     8998
2012    10962
2013    13799
2014    17531
Name: count, dtype: int64

In [61]:
df.drop(columns=["Order_Month"], errors="ignore", inplace=True)

In [62]:
df.columns

Index(['Category', 'City', 'Country', 'Customer_ID', 'Customer_Name',
       'Discount', 'Market', 'Order_Date', 'Order_ID', 'Order_Priority',
       'Product_ID', 'Product_Name', 'Profit', 'Quantity', 'Region', 'Row_ID',
       'Sales', 'Segment', 'Ship_Date', 'Ship_Mode', 'Shipping_Cost', 'State',
       'Sub_Category', 'Year', 'Market2', 'weeknum', 'Shipping_Days',
       'Order_Year', 'Quarter', 'Profit_Margin', 'Product_Short_Name'],
      dtype='object')

In [63]:
"Order_Month" in df.columns

False

In [64]:
# Msrket wise sales analysis
shipmode_sales=(df.groupby("Ship_Mode")["Sales"].
    sum().sort_values(ascending = False))
print(shipmode_sales)

Ship_Mode
Standard Class    7578889
Second Class      2565747
First Class       1831067
Same Day           667202
Name: Sales, dtype: int64

In [65]:
# Segment wise Sales
segment_sales=(df.groupby("Segment")["Sales"].sum().sort_values(ascending = False))
print(segment_sales)

Segment
Consumer       6508141
Corporate      3824808
Home Office    2309956
Name: Sales, dtype: int64

In [66]:
#Top 10 country wise sales
top_countries=(df.groupby("Country")["Sales"].sum().sort_values(ascending = False))
print(top_countries)

Country
United States        2297354
Australia             925257
France                858930
China                 700591
Germany               628857
                      ...
Tajikistan               242
Macedonia                210
Eritrea                  188
Armenia                  156
Equatorial Guinea        150
Name: Sales, Length: 147, dtype: int64

In [67]:
# Discount vs Profit Analysis
discount_profit=(df.groupby("Discount")[["Sales", "Profit"]].sum())
print(discount_profit)


# =====================================
# Business Insight
# =====================================

# Orders with no discount generated the highest profit.
# As the discount percentage increases, profit decreases.
# Discounts above 30% result in negative profit (loss).
# The company should review its high-discount strategy
# to improve overall profitability.

            Sales        Profit
Discount
0.000     6992734  1.770695e+06
0.002      261395  5.797658e+04
0.070      121620  2.114850e+04
0.100     1579618  2.590642e+05
0.150      306037  2.737590e+04
0.170      247404  2.816307e+04
0.200     1203855  1.177159e+05
0.202       16213 -5.952727e+02
0.250       88063  8.005875e+02
0.270       89351 -1.675079e+03
0.300      188913 -1.968585e+04
0.320       14491 -2.391138e+03
0.350       95704 -1.416965e+04
0.370       31615 -5.806202e+03
0.400      559557 -1.437485e+05
0.402       33737 -1.143045e+04
0.450       33397 -1.360679e+04
0.470       83432 -3.116225e+04
0.500      324145 -1.586299e+05
0.550        6308 -3.150672e+03
0.570        8144 -6.313548e+03
0.600      184586 -1.639547e+05
0.602        4977 -4.905419e+03
0.650        6580 -6.221966e+03
0.700      139770 -1.863505e+05
0.800       20462 -3.861623e+04
0.850         797 -3.068658e+03

In [68]:
# Export the cleaned dataset
df.to_csv("Global_Superstore_Cleaned.csv", index=False)

print("File exported successfully!")

File exported successfully!

In [69]:
# Export the cleaned dataset to Desktop
df.to_csv(r"C:\Users\Mr\OneDrive\Desktop\Global_Superstore_Cleaned.csv", index=False)

print("✅ File saved successfully on Desktop!")

✅ File saved successfully on Desktop!

In [70]:
df.to_csv(
    r"C:\Users\Mr\OneDrive\Desktop\Global_Superstore_Cleaned.csv",
    index=False,
    encoding="utf-8-sig"
)

print("File saved successfully!")

File saved successfully!

In [71]:
print(df.columns.tolist())

['Category', 'City', 'Country', 'Customer_ID', 'Customer_Name', 'Discount', 'Market', 'Order_Date', 'Order_ID', 'Order_Priority', 'Product_ID', 'Product_Name', 'Profit', 'Quantity', 'Region', 'Row_ID', 'Sales', 'Segment', 'Ship_Date', 'Ship_Mode', 'Shipping_Cost', 'State', 'Sub_Category', 'Year', 'Market2', 'weeknum', 'Shipping_Days', 'Order_Year', 'Quarter', 'Profit_Margin', 'Product_Short_Name']

In [72]:
df.to_csv(
    r"C:\Users\Mr\OneDrive\Desktop\Global_Superstore_Cleaned.csv",
    index=False,
    encoding="utf-8-sig"
)

print("File exported successfully!")

File exported successfully!

In [73]:
df.to_csv(
    r"C:\Users\Mr\OneDrive\Desktop\Global_Superstore_Cleaned.csv",
    index=False,
    encoding="utf-8-sig"
)

In [74]:
# Find object (text) columns
text_columns = df.select_dtypes(include="object").columns

# Check for non-ASCII characters
for col in text_columns:
    if df[col].astype(str).str.contains(r'[^\x00-\x7F]', regex=True).any():
        print(col)

City
Customer_Name
Product_Name
State
Product_Short_Name

In [75]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\mr\anaconda3\lib\site-packages (9.7.0)
Note: you may need to restart the kernel to use updated packages.

In [76]:
import mysql.connector

In [77]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Rekha@25",
    database="gsuperstore"
)

print("Connected Successfully!")

Connected Successfully!

In [78]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\mr\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\mr\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\users\mr\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\mr\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [79]:
from sqlalchemy import create_engine

In [86]:
engine = create_engine(
    "mysql+pymysql://root:Rekha@25@localhost/gsuperstore"
)

In [87]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Rekha%4025@localhost/gsuperstore"
)

In [88]:
print(df.shape)

(51290, 31)

In [90]:
df["Order_ID"].nunique()

25035

In [91]:
print("Total Rows:", len(df))
print("Unique Order IDs:", df["Order_ID"].nunique())

Total Rows: 51290
Unique Order IDs: 25035

In [92]:
import numpy as np

print("Positive Infinity:", np.isinf(df["Profit_Margin"]).sum())
print("Negative Infinity:", np.isneginf(df["Profit_Margin"]).sum())

Positive Infinity: 1
Negative Infinity: 1

In [93]:
import numpy as np

# Replace inf and -inf with NaN
df.replace([np.inf, -np.inf], np.nan, inplace=True)

# Fill NaN values in Profit_Margin with 0
df["Profit_Margin"] = df["Profit_Margin"].fillna(0)

In [94]:
print("Positive Infinity:", np.isinf(df["Profit_Margin"]).sum())
print("Negative Infinity:", np.isneginf(df["Profit_Margin"]).sum())
print("Null Values:", df["Profit_Margin"].isnull().sum())

Positive Infinity: 0
Negative Infinity: 0
Null Values: 0

In [96]:
df.to_sql(
    name="superstore",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data imported successfully!")

Data imported successfully!